/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlockUI: typeof import('primevue/blockui')['default']
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    CategoryAppList: typeof import('./src/components/CategoryAppList.vue')['default']
    CategoryList: typeof import('./src/components/CategoryList.vue')['default']
    CategoryListItem: typeof import('./src/components/CategoryListItem.vue')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    GridAppItem: typeof import('./src/components/GridAppItem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Popover: typeof import('primevue/popover')['default']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Select: typeof import('primevue/select')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    ThemeColorPicker: typeof import('./src/components/ThemeColorPicker.vue')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
